### PR TITLE
Update yakt.sh

### PR DESCRIPTION
**Pull request by CRANKV2**
Reworked and Improved Script

Description:
- Added a `write()` function to handle file writes more robustly.
- Enhanced logging with timestamps for better error tracking.
- Organized and cleaned up the code for readability.
- Created a dedicated directory for error log files inside main yakt MODDIR.
- Improved error handling with informative messages.
- Simplified file path checking and handling.

These changes make the script more reliable, easier to maintain, and provide better feedback in case of errors.

Contributor: @CRANKV2

### CODE REVIEW

**Comment by NotZeetaa** [comment]
Thank you.
I will review it later.

**Comment by CRANKV2** [comment]
Great!

Feel free to rework all like u want, hope it still helps 😁

**Comment by NotZeetaa** [comment]
@CRANKV2 What's ur GitHub email?

**Comment by NotZeetaa** [comment]
@CRANKV2 i commited has myself for now until u gave me ur email to author you, thank you for your contribution.

**Comment by CRANKV2** [comment]
> @CRANKV2 i commited has myself for now until u gave me ur email to author you, thank you for your contribution.

francesco2594@gmail.com

**Comment by NotZeetaa** [comment]
I didn't merge cause I didn't accepted it fully so I just committed and authored you here: https://github.com/NotZeetaa/YAKT/commit/72a5e12a6e52d58b4761efd992a9030e1a583723

**Comment by CRANKV2** [comment]
> I didn't merge cause I didn't accepted it fully so I just committed and authored you here: https://github.com/NotZeetaa/YAKT/commit/72a5e12a6e52d58b4761efd992a9030e1a583723 
> Thank you for your contribution

All good, as long it helps, I'm glad to help, thats one of my favorite projects 😁

**Pull request closed without merging**
